<?

$dia[1] = "um";
$dia[2] = "dois";
$dia[3] = "três";
$dia[4] = "quatro";
$dia[5] = "cinco";
$dia[6] = "seis";
$dia[7] = "sete";
$dia[8] = "oito";
$dia[9] = "nove";
$dia[10]= "dez";
$dia[11]= "oOnze";
$dia[12]= "doze";
$dia[13]= "treze";
$dia[14]= "quatorze";
$dia[15]= "quinze";
$dia[16]= "dezesseis";
$dia[17]= "dezessete";
$dia[18]= "dezoito";
$dia[19]= "dezenove";
$dia[20]= "vinte";
$dia[21]= "vinte e um";
$dia[22]= "vinde e dois";
$dia[23]= "vinte e tres";
$dia[24]= "vinte e quatro";
$dia[25]= "vinte e cinco";
$dia[26]= "vinte e seis";
$dia[27]= "vinte e sete";
$dia[28]= "vinte e oito";
$dia[29]= "vinte e nove";
$dia[30]= "trinta";
$dia[31]= "trinta e um";

$mes[1]  = "Janeiro";
$mes[2]  = "Fevereiro";
$mes[3]  = "Mar&ccedil;o";
$mes[4]  = "Abril";
$mes[5]  = "Maio";
$mes[6]  = "Junho";
$mes[7]  = "Julho";
$mes[8]  = "Agosto";
$mes[9]  = "Setembro";
$mes[10] = "Outubro";
$mes[11] = "Novembro";
$mes[12] = "Dezembro";


?>
