<html>
 <head>
  <title>.::TheFlockers::.</title>
  <link rel="stylesheet" type="text/css" href="<? include "config/config.php"; echo $style;?>style.css" />
   <script src="script.js">

</script>
   </head>
<body topmargin="0">
<center>
<div class="header"><img src="<?echo $style."images/admin_menu_01.png";?>" usemap="#btn1" border="0">
<!-- img src="<?echo $style."images/admin_menu_02.png";?>" usemap="#btn2" border="0" -->
<!-- img src="<?echo $style."images/admin_menu_03.png";?>" usemap="#btn3" border="0" -->
<img src="<?echo $style."images/admin_menu_04.png";?>" usemap="#btn4" border="0" -->
<img src="<?echo $style."images/menu_04.png";?>" usemap="#btn5" border="0">
<img src="<?echo $style."images/menu_05.png";?>" usemap="#btn6" border="0"><br/><span style="font-size:10px">&nbsp;</span>
</div>
</center>
 <map name="btn1">
  <area shape="rect" coords="28,89,72,108" href="logon.php?flag=domain">
  <area shape="circle" coords="50,52,34" href="logon.php?flag=domain">
 </map>
 <!-- map name="btn2">
  <area shape="rect" coords="28,89,72,108" href="logon.php?flag=ftp">
  <area shape="circle" coords="50,52,34" href="logon.php?flag=ftp">
 </map>
 <map name="btn3">
  <area shape="rect" coords="28,89,72,108" href="logon.php?flag=www">
  <area shape="circle" coords="50,52,34" href="logon.php?flag=www">
 </map -->
 <map name="btn4">
  <area shape="rect" coords="28,89,72,108" href="logon.php?flag=cadast">
  <area shape="circle" coords="50,52,34" href="logon.php?flag=cadast">
 </map>
 <map name="btn5">
  <area shape="rect" coords="28,89,72,108" href="logon.php?flag=filter">
  <area shape="circle" coords="50,52,34" href="logon.php?flag=filter">
 </map>
 <map name="btn6">
  <area shape="rect" coords="28,89,72,108" href="logon.php?destroy=s">
  <area shape="circle" coords="50,52,34" href="logon.php?destroy=s">
 </map>
