<div align="center" style="background-color: #ccccdd">
  <div style="text-align: justify; width:500px;">
   <blockquote>
   <br/>
   <span style="color:#000000">Extreme Post-MailAdmin</span><br/><br/>
   O Post-MailAdmin &eacute; uma solu&ccedil;&atilde;o completa que,
   usando a robustez do Banco de Dados PostgreSQL em conjunto com o 
   Postfix, Courier-Imap, Maildrop, SpamAssassin e TMDA, provê total
   controle no gerenciamento de servidores de E-mail.
   Sua costumização é simples, qualquer pessoa com os conhecimentos
   necessários em PHP, HTML e SQL poderá altera-lo.
   O Post-MailAdmin é uma solução Livre.<br/><br/>
   Em caso de necessidade de consultoria, entre com contato pelo e-mail
   <a href="mailto:theflockers@terra.com.br">theflockers@terra.com.br.</a><br/><br/><br/>


  <b>Leandro Mendes</b>
  </blockquote>
  <br/>
 </div>
<div>
