<form action="remdomain.php" method="POST">
<table border="0" width="500" bordercolor="green" align="center">
<tr><td>
 <table align="center" border="0" height="130"  width="400">
  <tr>
   <td  class="small_titulo" height="30" align="center" colspan="2">Remover Dom&iacute;nios</td>
  </tr>
  <tr>
   <td class="small_titulo" width="70">&nbsp;&nbsp;Dominio:</td>
   <td><input type="text" name="domain"></td>
  </tr>
  <tr>
   <td>&nbsp;</td>
   <td><input type="submit" value="Procurar">
  </tr>
 </table>
</td></tr>
</table>
</form>
</tb>
