<td class="menu" width=550 align=center>
<form action="remmailbox.php" method="POST">
<table border="0" width="500" bordercolor="green" align="center">
<tr><td>
 <table border="0" align="center" border="0" height="130"  width="400">
  <tr>
   <td colspan="3" class="small_titulo" height="30" align="center" colspan="2"><b>Remover E-mail (Mailbox)</b></td>
  </tr>
  <tr>
   <td class="small_titulo" width="70"><b>&nbsp;&nbsp;E-mail:</b></td>
   <td colspan="2"><input type="text" name="email"></td>
  </tr>
  <tr>
   <td>&nbsp;</td>
   <td align="right"><input type="submit" value="Procurar"></td>
   <td colspan="2" width="185">&nbsp;</td>
  </tr>
 </table>
</td></tr>
</table>
</form>
</tb>
